# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os

from PyQt6 import QtCore, QtGui, QtWidgets
from plyer import notification


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.is_runing = False
        self.is_time_work = True

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(392, 341)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_add_time_work = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_add_time_work.setGeometry(QtCore.QRect(280, 140, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_add_time_work.setFont(font)
        self.btn_add_time_work.setAutoDefault(False)
        self.btn_add_time_work.setObjectName("btn_add_time_work")
        self.btn_reduce_time_work = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_reduce_time_work.setGeometry(QtCore.QRect(190, 140, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_reduce_time_work.setFont(font)
        self.btn_reduce_time_work.setAutoDefault(False)
        self.btn_reduce_time_work.setObjectName("btn_reduce_time_work")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 140, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 190, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_add_time_chill = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_add_time_chill.setGeometry(QtCore.QRect(280, 190, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_add_time_chill.setFont(font)
        self.btn_add_time_chill.setAutoDefault(False)
        self.btn_add_time_chill.setObjectName("btn_add_time_chill")
        self.btn_reduce_time_chill = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_reduce_time_chill.setGeometry(QtCore.QRect(190, 190, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_reduce_time_chill.setFont(font)
        self.btn_reduce_time_chill.setAutoDefault(False)
        self.btn_reduce_time_chill.setObjectName("btn_reduce_time_chill")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 190, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(40, 250, 121, 41))
        self.btn_start.setObjectName("btn_start")
        self.txt_time_work = QtWidgets.QLabel(parent=self.centralwidget)
        self.txt_time_work.setGeometry(QtCore.QRect(220, 140, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txt_time_work.setFont(font)
        self.txt_time_work.setScaledContents(False)
        self.txt_time_work.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_time_work.setWordWrap(False)
        self.txt_time_work.setObjectName("txt_time_work")
        self.txt_time_chill = QtWidgets.QLabel(parent=self.centralwidget)
        self.txt_time_chill.setGeometry(QtCore.QRect(220, 190, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txt_time_chill.setFont(font)
        self.txt_time_chill.setScaledContents(False)
        self.txt_time_chill.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_time_chill.setWordWrap(False)
        self.txt_time_chill.setObjectName("txt_time_chill")
        self.txt_timer_minute = QtWidgets.QLabel(parent=self.centralwidget)
        self.txt_timer_minute.setGeometry(QtCore.QRect(120, 10, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.txt_timer_minute.setFont(font)
        self.txt_timer_minute.setScaledContents(False)
        self.txt_timer_minute.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txt_timer_minute.setWordWrap(False)
        self.txt_timer_minute.setObjectName("txt_timer_minute")
        self.txt_timer_second = QtWidgets.QLabel(parent=self.centralwidget)
        self.txt_timer_second.setGeometry(QtCore.QRect(200, 10, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.txt_timer_second.setFont(font)
        self.txt_timer_second.setScaledContents(False)
        self.txt_timer_second.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txt_timer_second.setWordWrap(False)
        self.txt_timer_second.setObjectName("txt_timer_second")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 15, 31, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_10.setFont(font)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.txt_status = QtWidgets.QLabel(parent=self.centralwidget)
        self.txt_status.setGeometry(QtCore.QRect(127, 65, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_status.setFont(font)
        self.txt_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_status.setObjectName("txt_status")
        self.btn_reset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(170, 250, 51, 41))
        self.btn_reset.setObjectName("btn_reset")
        self.btn_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(230, 250, 121, 41))
        self.btn_stop.setObjectName("btn_start_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiontime = QtGui.QAction(parent=MainWindow)
        self.actiontime.setObjectName("actiontime")
        # добавляем иконку
        if getattr(sys, 'frozen', False):
            image = os.path.join(sys._MEIPASS, 'logo.ico')
        else:
            image = 'logo.ico'
        icon = QtGui.QIcon(image)
        MainWindow.setWindowIcon(icon)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_functions(self):
        self.btn_start.clicked.connect(self.start)
        self.btn_stop.clicked.connect(self.stop)
        self.btn_reset.clicked.connect(self.reset)
        self.btn_add_time_chill.clicked.connect(self.add_time_chill)
        self.btn_reduce_time_chill.clicked.connect(self.reduce_time_chill)
        self.btn_add_time_work.clicked.connect(self.add_time_work)
        self.btn_reduce_time_work.clicked.connect(self.reduce_time_work)

    def start(self):
        self.is_runing = True
        self.timer = QtCore.QTimer()
        self.timer.setInterval(1000)  # Интервал 1 секунда
        self.timer.timeout.connect(self.update_timer)
        self.timer.start()

    def stop(self):
        self.timer.stop()

    def update_timer(self):
        current_minute = int(self.txt_timer_minute.text())
        current_second = int(self.txt_timer_second.text())

        if current_second == 0:
            if current_minute == 0:
                self.is_time_work = not self.is_time_work
                try:
                    self.show_notification()
                except Exception as e:
                    print(e)   
                if self.is_time_work:
                    current_minute = int(self.txt_time_work.text())
                    self.txt_status.setText('work...')
                else:
                    current_minute = int(self.txt_time_chill.text())
                    self.txt_status.setText('chill...')
            else:
                current_minute -= 1
                current_second = 59
        else:
            current_second -= 1

        if current_minute >= 10:
            self.txt_timer_minute.setText(str(current_minute))
        else:
            self.txt_timer_minute.setText('0' + str(current_minute))

        if current_second >= 10:
            self.txt_timer_second.setText(str(current_second))
        else:
            self.txt_timer_second.setText('0' + str(current_second))

    def reset(self):
        if self.is_runing:
            self.timer.stop()
        self.is_runing = False
        self.is_time_work = True
        self.txt_status.setText('work...')
        self.txt_timer_minute.setText('45')
        self.txt_timer_second.setText('00')
        self.txt_time_work.setText('45')
        self.txt_time_chill.setText('15')

    def add_time_chill(self):
        if not self.is_runing:
            cur_time = int(self.txt_time_chill.text())
            if cur_time < 90:
                self.txt_time_chill.setText(str(cur_time + 5))

    def reduce_time_chill(self):
        if not self.is_runing:
            cur_time = int(self.txt_time_chill.text())
            if cur_time > 5:
                self.txt_time_chill.setText(str(cur_time - 5))

    def add_time_work(self):
        if not self.is_runing:
            cur_time = int(self.txt_time_work.text())
            if cur_time < 90:
                self.txt_time_work.setText(str(cur_time + 5))
                self.txt_timer_minute.setText(self.txt_time_work.text())

    def reduce_time_work(self):
        if not self.is_runing:
            cur_time = int(self.txt_time_work.text())
            if cur_time > 5:
                self.txt_time_work.setText(str(cur_time - 5))
                self.txt_timer_minute.setText(self.txt_time_work.text())

    def show_notification(self):
        if not self.is_time_work:
            text_for_title = 'отдохнуть'
            text_for_message = 'отдыха'
            time = self.txt_time_chill.text()
        else:
            text_for_title = 'поработать'
            text_for_message = 'работы'
            time = self.txt_time_work.text()

        notification.notify(
            title=f'Пора {text_for_title}!',
            message=f'Время для {text_for_message}: {time} мин.',
            timeout=10
        )


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chill you eyes"))
        self.btn_add_time_work.setText(_translate("MainWindow", "+"))
        self.btn_reduce_time_work.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "Время для работы"))
        self.label_3.setText(_translate("MainWindow", "мин."))
        self.label_4.setText(_translate("MainWindow", "Время для отдыха"))
        self.btn_add_time_chill.setText(_translate("MainWindow", "+"))
        self.btn_reduce_time_chill.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "мин."))
        self.btn_start.setText(_translate("MainWindow", "СТАРТ"))
        self.txt_time_work.setText(_translate("MainWindow", "45"))
        self.txt_time_chill.setText(_translate("MainWindow", "15"))
        self.txt_timer_minute.setText(_translate("MainWindow", "45"))
        self.txt_timer_second.setText(_translate("MainWindow", "00"))
        self.label_10.setText(_translate("MainWindow", ":"))
        self.txt_status.setText(_translate("MainWindow", "work..."))
        self.btn_reset.setText(_translate("MainWindow", "СБРОС"))
        self.btn_stop.setText(_translate("MainWindow", "СТОП"))
        self.actiontime.setText(_translate("MainWindow", "time"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.add_functions()
    MainWindow.show()
    sys.exit(app.exec())
